version: "2"
services:
  ngrok:
    container_name: ngrok
    image: hteen/ngrok
    environment:
      - DOMAIN="liumapp.com"
    volumes:
      - ./client/:/data/ngrok/
    ports:
      - "3030:80"
      - "2243:443"
      - "4443:4443"
